### ISSUE TITLE
Globally disable without config?

### ISSUE THREAD

**Issue by DougPuchalski** [myronmarston/mail_safe#5]
The mere presence of this gem preventing emails from going out seems like a dangerous approach. Why require configuration to be both in the Gemfile and the initializer?

**Comment by myronmarston** [comment]
If you don't want mail safe to do anything, don't require it.

**Comment by DougPuchalski** [comment]
Bundler is pretty much the de-facto standard, and you can't exclude a named group as far as I know. Requiring a gem that has potentially dangerous side-effects might be something worth mulling over...

**Comment by myronmarston** [comment]
> Bundler is pretty much the de-facto standard, and you can't exclude a named group as far as I know. Requiring a gem that has potentially dangerous side-effects might be something worth mulling over...

I agree. That's why you shouldn't be auto-requiring any gems.

There are three solutions you can use with bundler:
- Use `Bundler.setup` rather than `Bundler.require`.  `setup` sets up your load path but does not auto-require gems. I think it's the best way to use bundler anyway...I really dislike bundler's auto-requiring functionality.  It's a great way to get an app with really slow boot times.
- Use `Bundler.require(:group1, :group2)`, and put put `mail_safe` in one of the other groups.
- add `:require => nil` to the gem declaration in your Gemfile.
